hotfix/3.1.2
CanalTP/CDVNavitiaSDK pull request #59
Opened 2022-01-27 11:21 UTC by EvenModiguy

2022-01-31 09:51 UTC, MikePetitfils submitted a review, later dismissed

2022-01-31 15:01 UTC, RachikAbidi requested changes

2022-02-01 08:44 UTC, RachikAbidi requested changes
Where are the changes? What is the need of this hotfix?

2022-02-01 09:36 UTC, RachikAbidi approved these changes

2022-02-01 09:37 UTC, merged